//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeMovieManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film_Director
    {
        public int id { get; set; }
        public Nullable<int> Film_id { get; set; }
        public Nullable<int> Director_id { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Film Film { get; set; }
    }
}
