//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeMovieManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int id { get; set; }
        public string code { get; set; }
        public string releasePeriod { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public Nullable<int> quantities { get; set; }
        public Nullable<int> denomination { get; set; }
    }
}
