//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.Showtimes = new HashSet<Showtime>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string genre { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> publishedYear { get; set; }
        public Nullable<int> rating { get; set; }
        public string poster { get; set; }
        public string certification { get; set; }
        public Nullable<int> Actor { get; set; }
        public Nullable<int> Director { get; set; }
        public string plotSummary { get; set; }
    
        public virtual Actor Actor1 { get; set; }
        public virtual Director Director1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Showtime> Showtimes { get; set; }
    }
}
