//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public movie()
        {
            this.showtimes = new HashSet<showtime>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string genre { get; set; }
        public Nullable<int> duration { get; set; }
        public Nullable<System.DateTime> publishedYear { get; set; }
        public Nullable<int> rating { get; set; }
        public string poster { get; set; }
        public string certification { get; set; }
        public Nullable<int> actor { get; set; }
        public Nullable<int> director { get; set; }
        public Nullable<int> showtime { get; set; }
    
        public virtual actor actor1 { get; set; }
        public virtual director director1 { get; set; }
        public virtual showtime showtime1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<showtime> showtimes { get; set; }
    }
}
